#%RAML 1.0 DataType
type: object
properties:
  ComplaintID?: string
  CustID: string
  OrderID: string
  OrderDate: string
  ProductID: string
  ProductName: string
  ProductPrice: integer
  ComplaintDesc: string
  ComplaintStatus: string